[package]
name = "ble-chirp"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
hex = "0.4"
anyhow = "1"
